"""Constants for sunseeker integration."""

SERIAL_NO = "serial_no"
DOMAIN = "sunseeker"
ROBOTS = "robots"
DATAHANDLER = "DATAHANDLER"
DH = "dh"

SUNSEEKER_STANDBY = "Standby"
SUNSEEKER_MOWING = "Mowing"
SUNSEEKER_GOING_HOME = "On the way home"
SUNSEEKER_CHARGING = "Charging"
SUNSEEKER_MOWING_BORDER = "Mowing border"
SUNSEEKER_UNKNOWN_4 = "Unknown4"
SUNSEEKER_UNKNOWN = "Unknown"

SUNSEEKER_IDLE = "Idle"
SUNSEEKER_WORKING = "Working"
SUNSEEKER_PAUSE = "Pause"
SUNSEEKER_ERROR = "Error"
SUNSEEKER_RETURN = "Return"
SUNSEEKER_RETURN_PAUSE = "Return pause"
SUNSEEKER_CHARGING = "Charging"
SUNSEEKER_CHARGING_FULL = "Charging full"
SUNSEEKER_OFFLINE = "Offline"
SUNSEEKER_LOCATING = "Locating"
SUNSEEKER_STOP = "Stop"

SUNSEEKER_DRY = "Dry"
SUNSEEKER_WET = "Wet"
SUNSEEKER_DRY_COUNTDOWN = "Dry countdown"

# Max retries
MAX_LOGIN_RETRIES = 10
MAX_SET_CONFIG_RETRIES = 5

# APPTYPE = "app_type"
