start_mowing:
  name: Start mowing
  description: >
    Start the mower and optionally specify a list of zones to mow.
    If no zones are provided, the mower will use its default behavior.
  fields:
    entity_id:
      name: Mower entity
      description: The mower entity to control.
      required: true
      selector:
        entity:
          domain: lawn_mower
    zones:
      name: Zones
      description: A list of zone names to mow.
      required: true
      example: ["Front yard", "Back yard"]
      selector:
        object: {}

stop_mowing:
  name: Stop mowing
  description: >
    Stops the mower.
  fields:
    entity_id:
      name: Mower entity
      description: The mower entity to control.
      required: true
      selector:
        entity:
          domain: lawn_mower

set_pin:
  name: Change pin
  description: >
    Change the mowers 4 digit pin code.
  fields:
    entity_id:
      name: Mower entity
      description: The mower entity.
      required: true
      selector:
        entity:
          domain: lawn_mower
    old_pin:
      name: Old pin code
      description: The mowers old 4 digits pin code.
      required: true
      selector:
        text:
    new_pin:
      name: New pin code
      required: true
      description: The mowers new 4 digits pin code.
      selector:
        text:

set_schedule:
  name: Set schedule
  description: >
    Set the mowing schedule for your Sunseeker mower. You must provide the mower entity and a complete schedule object.
  fields:
    entity_id:
      name: Sensor entity with schedule add to attributes
      description: The mowers sensor entity to set the schedule for.
      required: true
      selector:
        entity:
          domain: sensor
    schedule:
      name: Schedule
      description: >
        The schedule data to apply. This must be a dictionary matching the expected schedule format, including all days and options.
      required: true
      example: |
        {
          "recommended_time_work": false,
          "user_defined": true,
          "pause": false,
          "locations": ["Front", "Back"],
          "monday": [
            {
              "enabled": true,
              "starttime": "08:00",
              "endtime": "10:00",
              "locations": ["Front"]
            },
            {
              "enabled": false,
              "starttime": "00:00",
              "endtime": "00:00",
              "locations": []
            }
          ],
          "tuesday": [],
          "wednesday": [],
          "thursday": [],
          "friday": [],
        }

set_map:
  name: Set map
  description: >
    Set the map data for your Sunseeker mower. You must provide the mower entity and a complete map object.
  fields:
    entity_id:
      name: Image entity with map add to attributes
      description: The mowers Image entity to set the map for.
      required: true
      selector:
        entity:
          domain: image
    schedule:
      name: Map data
      description: >
        The map data to apply. This must be a dictionary matching the expected map format.
      required: true
      example: |
        Use the sunseeker-map-edit-card.

restore_map:
  name: Restore map
  description: >
    Restores map from backup for your Sunseeker mower.
  fields:
    entity_id:
      name: Mower entity
      description: The mower entity.
      required: true
      selector:
        entity:
          domain: lawn_mower
    mapid:
      name: Mapid to restore
      description: The backup mapid to restore.
      required: true
      selector:
        text:
backup_map:
  name: Backup map
  description: >
    Backup the curret map for your Sunseeker mower.
  fields:
    entity_id:
      name: Mower entity
      description: The mower entity.
      required: true
      selector:
        entity:
          domain: lawn_mower
    mapid:
      name: Mapid to restore
      description: The backup mapid to restore.
      required: true
      selector:
        text:
