name: Lint

on:
  push:
    branches:
      - main

jobs:
  ruff:
    name: Check Python syntax
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          args: "check --select E999"
